# Generated by Django 2.2.1 on 2019-08-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAMPUS_ID', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Course_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=100)),
                ('courseno', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('md', models.DateField(null=True)),
                ('mt', models.CharField(max_length=100, null=True)),
                ('cd', models.DateField(null=True)),
                ('ct', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
